CREATE TABLE BOOK(
    BOOK_NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(50) NOT NULL,
    AUTHOR VARCHAR2(30) NOT NULL,
    PUBLISHER VARCHAR2(50) NOT NULL,
    PRICE NUMBER,
    STOCK NUMBER DEFAULT 0 NOT NULL,
    REGIST_DATE DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN BOOK.BOOK_NO IS '도서번호';
COMMENT ON COLUMN BOOK.TITLE IS '제목';
COMMENT ON COLUMN BOOK.AUTHOR IS '저자명';
COMMENT ON COLUMN BOOK.PUBLISHER IS '출판사명';
COMMENT ON COLUMN BOOK.PRICE IS '가격';
COMMENT ON COLUMN BOOK.STOCK IS '재고';
COMMENT ON COLUMN BOOK.REGIST_DATE IS '도서등록일';

CREATE SEQUENCE SEQ_BOOKNO;

INSERT INTO BOOK VALUES(SEQ_BOOKNO.NEXTVAL, '자바의 정석', '남궁석', '나무', 20000, 100, DEFAULT);
INSERT INTO BOOK VALUES(SEQ_BOOKNO.NEXTVAL, 'C언어의 모든것', 'C장인', 'IT출판', 30000, 20, DEFAULT);
INSERT INTO BOOK VALUES(SEQ_BOOKNO.NEXTVAL, '프로젝트 계획짜기', '프젝신', '보람찬하루', 10000, 35, DEFAULT);

COMMIT;